apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: devsecops
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
