name: DevSecOps CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tfsec:
    name: Terraform Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

  trivy:
    name: Docker Image Scan
    runs-on: ubuntu-latest
    needs: tfsec
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t myapp:latest .
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:latest
          format: table
          exit-code: 1
          ignore-unfixed: true

  deploy:
    name: Trigger AWS CodePipeline
    runs-on: ubuntu-latest
    needs: trivy
    env:
      AWS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        if: ${{ env.AWS_KEY != '' && env.AWS_SECRET != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Trigger AWS CodePipeline
        if: ${{ env.AWS_KEY != '' && env.AWS_SECRET != '' }}
        run: |
          aws codepipeline start-pipeline-execution \
            --name DevOps2025Pipeline \
            --region ap-south-1

