name: DevSecOps CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tfsec:
    name: Terraform Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true  # <---- allow pipeline to continue even if issues found

  trivy:
    name: Docker Image Scan
    runs-on: ubuntu-latest
    needs: tfsec
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t myapp:latest .
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:latest
          format: table
          exit-code: 0  # <---- optional: set to 0 to continue even if vulnerabilities are found
          ignore-unfixed: true

  deploy:
    name: Trigger AWS CodePipeline
    runs-on: ubuntu-latest
    needs: trivy
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Trigger AWS CodePipeline
        run: |
          aws codepipeline start-pipeline-execution --name DevOps2025Pipeline --region ap-south-1
